apiVersion: apps/v1
kind: Deployment
metadata:
  name: very-secure-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verysecureapp
  template:
    metadata:
      labels:
        app: verysecureapp
    spec:
      containers:
        - name: verysecureapp
          image: tushardevsharma/very-secure-app:v0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: my-k8s-secret
            items:
              - key: v2-acc
                path: v2-acc-file
              - key: v3-acc
                path: v3-acc-file