apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: my-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: v3-acc
      remoteRef:
        key: matrix-sec             # AWS Secrets Manager secret name
        property: v3                # AWS secret field name
    - secretKey: v2-acc
      remoteRef:
        key: matrix-sec
        property: v2
