apiVersion: v1
kind: Service
metadata:
  name: very-secure-app-service
spec:
  type: NodePort
  selector:
    app: verysecureapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32001
      protocol: TCP